# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - 'go run . -input foo/foo.go -output foo/com.go'
    silent: true

  gen:
    cmds:
      - 'rm -rf temp'
      - 'mkdir -p temp'
      - 'go run . -input data/def.yaml -output temp/com.go -pkg temp'